Intl.Realty.Firm/Controllers/DocumentTypeAssignmentController.cs
using Intl.Realty.Firm.Models.Models;
using Intl.Realty.Firm.Models.Models.ViewModel.DocumentTypeAssignmentVM;
using Intl.Realty.Firm.Repository.IRepository;
using Intl.Realty.Firm.Utility.Mapper;
using Intl.Realty.Firm.Utility.Utilities;
using Microsoft.AspNetCore.Mvc;

namespace Intl.Realty.Firm.Controllers
{
    public class DocumentTypeAssignmentController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private int _userId = 1;
        public DocumentTypeAssignmentController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> CreateModal()
        {
            CreateDocumentTypeAssignmentViewModel viewModel = new CreateDocumentTypeAssignmentViewModel();
            var transactionTypeIEnum = await _unitOfWork.TransactionType.GetAllAsync();
            var documentTypeIEnum = await _unitOfWork.DocumentType.GetAllAsync();
            viewModel.TransactionTypeIEnum = SelectListConverter.CreateSelectList(transactionTypeIEnum.ToList(), x => x.Id, x => x.Description);
            viewModel.DocumentTypeIEnum = SelectListConverter.CreateSelectList(documentTypeIEnum.ToList(), x => x.Id, x => x.Description);

            return PartialView("~/Views/DocumentTypeAssignment/Modal/CreateModal.cshtml", viewModel);
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateDocumentTypeAssignmentViewModel viewModel)
        {
            var modelList = await _unitOfWork.DocumentTypeAssignment.GetAllAsync(x => x.TransactionTypeId == viewModel.TransactionTypeId, includeProperties: "DocumentType,TransactionType");
            if (modelList.Any())
            {
                var modelCheckIfExists = modelList.Where(x => x.DocumentTypeId == viewModel.DocumentTypeId);
                if (modelCheckIfExists.Any())
                {
                    ModelState.AddModelError("name", "Document Type assignment already exists");
                }
            }

            viewModel.TransactionTypeId = viewModel.TransactionTypeId;
            viewModel.DocumentTypeId = viewModel.DocumentTypeId;
            viewModel.CreatedBy = 1;
            viewModel.IsActive = true;
            viewModel.CreatedAt = DateTime.UtcNow;

            var model = viewModel.ToDocumentTypeAssignmentModel();

            if (ModelState.IsValid)
            {
                await _unitOfWork.DocumentTypeAssignment.AddAsync(model);
                _unitOfWork.Save();
                TempData["success"] = "DocumentType Assignment created successfully";
                return RedirectToAction(nameof(Index), new { addSuccess = true });
            }
            return RedirectToAction(nameof(Index), new { addSuccess = false });

        }
        public async Task<IActionResult> EditModal(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            DocumentTypeAssignment? model = await _unitOfWork.DocumentTypeAssignment.GetAsync(u => u.Id == id);

            model.UpdatedBy = 1;
            model.UpdatedAt = DateTime.UtcNow;

            if (model == null)
            {
                return NotFound();
            }

            EditDocumentTypeAssignmentViewModel viewModel = model.ToEditDocumentTypeAssignmentModel();
            var transactionTypeIEnum = await _unitOfWork.TransactionType.GetAllAsync();

            var documentTypeIEnum = await _unitOfWork.DocumentType.GetAllAsync();
            viewModel.TransactionTypeList = transactionTypeIEnum.ToList();
            viewModel.DocumentTypeList = documentTypeIEnum.ToList();
            return PartialView("~/Views/DocumentTypeAssignment/Modal/EditModal.cshtml", viewModel);
        }
        [HttpPut]
        public async Task<IActionResult> Edit(int id, DocumentTypeAssignmentViewModel viewModel)
        {
            DocumentTypeAssignment? model = await _unitOfWork.DocumentTypeAssignment.GetAsync(u => u.Id == viewModel.Id);

            model.TransactionTypeId = viewModel.TransactionTypeId;
            model.DocumentTypeId = viewModel.DocumentTypeId;
            model.IsActive = viewModel.IsActive;
            model.UpdatedBy = 1;
            model.UpdatedAt = DateTime.UtcNow;

            await _unitOfWork.DocumentTypeAssignment.UpdateAsync(model);
            _unitOfWork.Save();
            TempData["success"] = "Document Type Assignment updated successfully";
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> ListPartialView()
        {
            var modelList = await _unitOfWork.DocumentTypeAssignment.GetAllAsync(includeProperties: "DocumentType,TransactionType");

            var viewModel = modelList.ToDocumentTypeAssignmentListViewModel();

            return PartialView("~/Views/DocumentTypeAssignment/Partial/ListPartial.cshtml", viewModel);
        }
        [HttpGet]
        public async Task<IActionResult> DeleteModal(int id)
        {
            var model = await _unitOfWork.DocumentTypeAssignment.GetAsync(x => x.Id == id);
            if (model == null)
            {
                return NotFound();
            }

            var editDocumentTypeAssignmentViewModel = model.ToEditDocumentTypeAssignmentViewModel();

            return PartialView("~/Views/DocumentTypeAssignment/Modal/DeleteModal.cshtml", editDocumentTypeAssignmentViewModel);
        }

        public async Task<IActionResult> DeleteMultipleModal(List<int> ids)
        {
            List<DocumentTypeAssignment> modelList = new List<DocumentTypeAssignment>();
            foreach (var id in ids)
            {
                var model = await _unitOfWork.DocumentTypeAssignment.GetAsync(x => x.Id == id);
                modelList.Add(model);
            }

            if (modelList == null)
            {
                return NotFound();
            }

            var transactionTypeViewModelList = modelList.ToDocumentTypeAssignmentListViewModel();

            IEnumerable<DocumentTypeAssignmentViewModel> modelIEnum = transactionTypeViewModelList.AsEnumerable();

            return PartialView("~/Views/DocumentTypeAssignment/Modal/DeleteMultipleModal.cshtml", modelIEnum);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            DocumentTypeAssignment? obj = await _unitOfWork.DocumentTypeAssignment.GetAsync(u => u.Id == id);

            if (obj == null)
            {
                return NotFound();
            }
            await _unitOfWork.DocumentTypeAssignment.RemoveAsync(obj);
            _unitOfWork.Save();
            TempData["success"] = "DocumentTypeAssignment deleted successfully";
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> DeleteMultiple(IEnumerable<DocumentTypeAssignmentViewModel> viewModelList)
        {
            if (viewModelList == null || !viewModelList.Any())
            {
                return RedirectToAction(nameof(Index));
            }

            var ids = viewModelList.Select(o => o.Id).ToList();
            var tramsactonTypeList = await _unitOfWork.DocumentTypeAssignment.GetAllAsync();
            var modelList = tramsactonTypeList.Where(o => ids.Contains(o.Id)).ToList();

            if (modelList != null)
            {
                try
                {
                    await _unitOfWork.DocumentTypeAssignment.RemoveRangeAsync(modelList);
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }

            }

            return StatusCode(StatusCodes.Status200OK, ModelState);
        }
    }
}

Intl.Realty.Firm/Views/DocumentTypeAssignment/Partial/DocumentTypeAssignmentListPartial.cshtml
@using Intl.Realty.Firm.Models.Models.ViewModel.DocumentTypeAssignmentVM
@model List<DocumentTypeAssignmentViewModel>

<div>
    <div class="row">
        <div class="col-md-12 d-flex justify-content-md-between align-items-center">
            <h1 class="text-blue mb-0">Document Types Assignment</h1>
            <div class="d-flex gap-4">
                <button id="btnDeleteDocumentTypeAssignment" class="btn btn-danger d-none align-items-center" data-bs-toggle="modal" data-bs-target="#deleteConfirmModal"><i data-feather="x" class="w-15px h-auto me-1"></i>Delete</button>
                <a asp-action="Create"
                   class="btn btn-primary d-flex align-items-center">
                    <i data-feather="plus" class="w-15px h-auto me-1"></i>Create New
                </a>
            </div>
        </div>
    </div>
    <form method="post" asp-action="DeleteMultiple" class="pt-4">
        <table id="documentTypeAssignmentTable" class="data-table table table-hover w-100">
            <thead>
                <tr>
                    <th class="text-center w-5">
                        <input type="checkbox" class="column-checkbox" data-toggle="tooltip" data-bs-placement="left" title="Select all">
                    </th>
                    <th>
                        PositionId
                    </th>
                    <th>
                        Transaction Type
                    </th>
                    <th>
                        Document Type
                    </th>

                    <th>
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>

                @{
                    var count = 0;
                }
                @foreach (var item in Model)
                {
                    count++;
                    <tr data-documentType-id="@item.Id">
                        <td class="text-center align-middle"> <input type="checkbox" class="row-checkbox" name="ids" value="@item.Id" /></td>
                        <td class="align-middle">
                            @{
                                @count.ToString()
                            }
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => @item.TransactionType.Name)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => @item.DocumentType.Name)
                        </td>

                        <td class="align-middle">
                            <a asp-action="Edit" asp-route-id="@item.Id" style="text-decoration: none;">
                                <span class="table-control-btn pe-3" title="edit" data-position-id="@item.Id">
                                    <i data-feather="edit" class="data-feather-20"></i>
                                    Edit
                                </span>
                            </a>
                            <a href="#"
                               type="button"
                               data-bs-toggle="modal"
                            @* data-bs-target="#deletePositionModal" *@
                               onclick="OpenDeleteModal(@item.Id)"
                               style="text-decoration: none;">
                                <span class="table-control-btn icon-red" title="delete" data-position-id="@item.Id">
                                    <i data-feather="trash-2" class="data-feather-20"></i>
                                    Delete
                                </span>
                            </a>
                        </td>
                    </tr>
                }


            </tbody>
        </table>

    </form>
</div>

<script>
    $(document).ready(function () {
        $('.data-table').DataTable({
            columnDefs: [
                { targets: [0], orderable: false }
            ],
            order: [[1, 'asc']]
        });

        $('#documentTypeAssignmentTable').on('click', 'tbody tr', function (event) {
            // Check if the clicked element is not the checkbox
            if (!$(event.target).is(':checkbox')) {
                var documentTypeId = $(this).data('documentType-id');
                window.location.href = '@Url.Action("Edit", "DocumentTypeAssignment")' + '?id=' + documentTypeId;
            }
        });

        $('.column-checkbox').change(function () {
            var isChecked = $(this).prop('checked');
            $('.row-checkbox').prop('checked', isChecked);
        });

        $('#documentTypeAssignmentTable').on('change', '.column-checkbox', function () {
            var isChecked = $(this).prop('checked');
            $('.row-checkbox').prop('checked', isChecked);

        });

        $('#documentTypeAssignmentTable').on('change', '.row-checkbox', function () {
            var isChecked = $(this).prop('checked');

            var allChecked = $('.row-checkbox').length === $('.row-checkbox:checked').length;
            $('.column-checkbox').prop('checked', allChecked);

        });

        $('#documentTypeAssignmentTable').on('change', '.row-checkbox, .column-checkbox', function () {
            var atLeastOneChecked = $('.row-checkbox:checked').length > 0;
            $('#btnDeleteDocumentTypeAssignment').toggleClass('d-none', !atLeastOneChecked);
            $('#btnDeleteDocumentTypeAssignment').toggleClass('d-flex', atLeastOneChecked);

            if ($(this).hasClass('column-checkbox')) {
                var isChecked = $(this).prop('checked');
                $('.row-checkbox').prop('checked', isChecked);
            }
        });

        $('.row-checkbox').change(function () {
            var allChecked = $('.row-checkbox').length === $('.row-checkbox:checked').length;
            $('.column-checkbox').prop('checked', allChecked);
        });

        if (getUrlParameter('deleteSuccess') === 'true') {
            toastr.success('Selection deleted successfully!', '', {
                timeOut: 10000,
                closeButton: true,
                onHidden: function () {
                    updateUrlParameter('deleteSuccess', '');
                }
            });
        }

        $('#btnConfirmDelete').click(function () {
            $('#deleteConfirmModal').modal('hide');
            window.location.href = window.location.href.split('?')[0] + '?deleteSuccess=true';
        });
    });

    $("#cancelBtn").click(function () {
        closeModal();
    });

    function OpenMultipleDeleteModal() {
        var selectedRows = getSelectedRows();
        var selectedIdsArray = getIdsFromSelectedRows(selectedRows);

        var allChecked = $('.row-checkbox').length === $('.row-checkbox:checked').length;
        $('.column-checkbox').prop('checked', allChecked);

        $('#documentTypeAssignmentDeleteMultipleModalContainer').load('/DocumentTypeAssignment/DeleteMultipleModal/', { ids: selectedIdsArray }, function () {
            $("#deleteConfirmModal").modal("show");
        });
    }

    function getIdsFromSelectedRows(selectedRows) {
        var ids = [];
        for (var i = 0; i < selectedRows.length; ++i)
            ids.push(selectedRows[i].value);
        return ids;
    }

    function OpenDeleteModal(id) {

        $('#documentTypeAssignmentDeleteModalContainer').load('/DocumentTypeAssignment/DeleteModal/' + id, function () {

            $("#deleteConfirmModal").modal("show");
        });
    }

</script>

Intl.Realty.Firm/Views/DocumentTypeAssignment/Partial/ListPartial.cshtml
@using Intl.Realty.Firm.Models.Models.ViewModel.DocumentTypeAssignmentVM
@model IEnumerable<DocumentTypeAssignmentViewModel>


<div>
    <form id="ListFormId" method="post">

        <div class="row">
            <div class="col-md-12 d-flex justify-content-md-between align-items-center">
                <h1 class="text-blue mb-0">DocumentTypeAssignments</h1>
                <div class="d-flex gap-2">
                    <a id="btnMultipleDelete"
                            class="btn btn-danger d-none align-items-center px-4"
                            data-toggle="tooltip"
                            data-bs-placement="left"
                            title="Delete"
                            onclick="OpenMultipleDeleteModal()">
                        <i data-feather="trash-2"></i> Delete
                    </a>

                    <a href="#"
                       class="btn btn-primary d-flex align-items-center"
                       type="button"
                       data-bs-toggle="modal"
                       onclick="OpenCreateModal()"
                       style="text-decoration: none;">
                        <span class="px-1 pb-1" title="create">
                            <i data-feather="plus" class="w-15px h-auto me-1"></i>
                            Add New
                        </span>
                    </a>
                </div>
            </div>
        </div>

        <div class="table-responsive mt-4">
            <table id="modelTable" class="data-table table-striped table table-hover w-100">
                <thead>
                    <tr>
                        <th class="text-lg-start align-middle w-5" width="5%">
                            <input id="select_all" type="checkbox" class="column-checkbox" data-toggle="tooltip" data-bs-placement="left" title="Select all">
                        </th>
                        <th class="text-lg-start align-middle">
                            Transaction Type
                        </th>
                        <th class="text-lg-start align-middle">
                            Document Type
                        </th>
                        <th class="text-lg-start align-middle">
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <input type="hidden" name="id" id="@item.Id" />
                            <td class="text-lg-start align-middle" width="5%">
                                <input type="checkbox" class="row-checkbox" name="selectedRows" id="selectedRows" value="@item.Id" />
                            </td>
                            <td id="transactionType" class="text-lg-start align-middle">
                                @Html.DisplayFor(modelItem => item.TransactionType.Description)
                            </td>
                            <td id="documentName" class="text-lg-start align-middle">
                                @Html.DisplayFor(modelItem => item.DocumentType.Description)
                            </td>
                            <td class="align-middle">
                                <a href="#"
                                   class="cta-edit btn p-0 m-0"
                                   data-bs-toggle="modal"
                                   onclick="OpenEditModal(@item.Id)"
                                   style="text-decoration: none;">
                                    <i data-feather="edit" class="h-auto me-1"></i>Update
                                    @* <span class="px-1 pb-1" title="edit">
                                        <i data-feather="edit" class="h-auto me-1"></i>
                                    </span> *@
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </form>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        feather.replace();
        $('[data-toggle="tooltip"]').tooltip();

        $('.data-table').DataTable({
            columnDefs: [
                { targets: [0], orderable: false },
                { targets: [1,2], orderable: true },
            ],
            order: [[1, 'asc']]
        });

        $('[id^=dt-search]').attr('placeholder', 'Search...').addClass('fst-italic');


        $('.column-checkbox').change(function () {
            var isChecked = $(this).prop('checked');
            $('.row-checkbox').prop('checked', isChecked);
        });

        $('#modelTable').on('change', '.column-checkbox', function () {
            var isChecked = $(this).prop('checked');
            $('.row-checkbox').prop('checked', isChecked);

        });

        $('#modelTable').on('change', '.row-checkbox', function () {
            var isChecked = $(this).prop('checked');

            var allChecked = $('.row-checkbox').length === $('.row-checkbox:checked').length;
            $('.column-checkbox').prop('checked', allChecked);

        });

        $('#modelTable').on('change', '.row-checkbox, .column-checkbox', function () {
            var atLeastOneChecked = $('.row-checkbox:checked').length > 0;
            $('#btnMultipleDelete').toggleClass('d-none', !atLeastOneChecked);
            $('#btnMultipleDelete').toggleClass('d-flex', atLeastOneChecked);

            if ($(this).hasClass('column-checkbox')) {
                var isChecked = $(this).prop('checked');
                $('.row-checkbox').prop('checked', isChecked);
            }
        });

        $('.row-checkbox').change(function () {
            var allChecked = $('.row-checkbox').length === $('.row-checkbox:checked').length;
            $('.column-checkbox').prop('checked', allChecked);
        });

        $('#btnConfirmDelete').click(function () {
            $('#deleteConfirmModal').modal('hide');
            window.location.href = window.location.href.split('?')[0] + '?deleteSuccess=true';
        });

        $("#cancelBtn").click(function () {
            closeModal();
        });

        handleToastrNotification('addSuccess', 'New transaction type added successfully!');
        handleToastrNotification('editSuccess', 'Transaction type updated successfully!');
        handleToastrNotification('deleteSuccess', 'Transaction type deleted successfully!');
    });

    function closeModal() {
        $("#deleteConfirmModal").modal("hide");
        let elem = document.querySelector('#deleteConfirmModal');
        elem.parentNode.removeChild(elem);
    }

    function OpenMultipleDeleteModal() {
        var selectedRows = getSelectedRows();
        var selectedIdsArray = getIdsFromSelectedRows(selectedRows);

        var allChecked = $('.row-checkbox').length === $('.row-checkbox:checked').length;
        $('.column-checkbox').prop('checked', allChecked);

        $('#DeleteMultipleModalContainer').load('/DocumentTypeAssignment/DeleteMultipleModal/', { ids: selectedIdsArray }, function () {
            $("#deleteConfirmModal").modal("show");
        });
    }

    function getIdsFromSelectedRows(selectedRows) {
        var ids = [];
        for (var i = 0; i < selectedRows.length; ++i)
            ids.push(selectedRows[i].value);
        return ids;
    }
    function OpenCreateModal() {
        $('#CreateModalContainer').load('/DocumentTypeAssignment/CreateModal/', function () {
            $("#createModal").modal("show");
        });
    }
    function OpenEditModal(id) {
        $('#EditModalContainer').load('/DocumentTypeAssignment/EditModal/' + id, function () {
            $("#editModal").modal("show");
        });
    }
    function OpenDeleteModal(id) {

        $('#DeleteModalContainer').load('/DocumentTypeAssignment/DeleteModal/' + id, function () {

            $("#deleteConfirmModal").modal("show");
        });
    }
    function ClearSearch() {
        $("#dt-search-0").val("").keyup();
    }

    function getSelectedRows() {
        var table = $('#modelTable').dataTable();
        selectedRows = table.find('input[name="selectedRows"]:checked').serializeArray();

        return selectedRows;
    }
</script>